"""initial schema

Revision ID: 882ca39fc43f
Revises: 
Create Date: 2026-06-22 21:49:57.355555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '882ca39fc43f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('caller_name', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('assigned_script', sa.String(length=50), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_queue', schema=None) as batch_op:
        batch_op.create_index('idx_queue_dialable', ['status', 'priority', 'next_attempt_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_queue_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_queue_phone_number'), ['phone_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_queue_status'), ['status'], unique=False)

    op.create_table('dnc_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dnc_list', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dnc_list_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_dnc_list_phone_number'), ['phone_number'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active_flag', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('queue_item_id', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('caller_name', sa.String(length=100), nullable=True),
    sa.Column('call_sid', sa.String(length=64), nullable=True),
    sa.Column('call_status', sa.String(length=20), nullable=False),
    sa.Column('response', sa.String(length=20), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['queue_item_id'], ['call_queue.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.create_index('idx_log_phone_created', ['phone_number', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_logs_call_sid'), ['call_sid'], unique=True)
        batch_op.create_index(batch_op.f('ix_call_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_logs_phone_number'), ['phone_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_logs_queue_item_id'), ['queue_item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_logs_queue_item_id'))
        batch_op.drop_index(batch_op.f('ix_call_logs_phone_number'))
        batch_op.drop_index(batch_op.f('ix_call_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_call_logs_call_sid'))
        batch_op.drop_index('idx_log_phone_created')

    op.drop_table('call_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('dnc_list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dnc_list_phone_number'))
        batch_op.drop_index(batch_op.f('ix_dnc_list_created_at'))

    op.drop_table('dnc_list')
    with op.batch_alter_table('call_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_queue_status'))
        batch_op.drop_index(batch_op.f('ix_call_queue_phone_number'))
        batch_op.drop_index(batch_op.f('ix_call_queue_created_at'))
        batch_op.drop_index('idx_queue_dialable')

    op.drop_table('call_queue')
    # ### end Alembic commands ###
